[package]
name = "pcap_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap-parser = "0.3.0"
cookie-factory = "0.2.4"
byteorder = "1.5.0"
nom = "7.1.3"
rusticata-macros = "1.1.0"