# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = ["influxdb", "influxdb_derive", "benches"]

[patch.crates-io]
influxdb = { path = "./influxdb" }
influxdb_derive = { path = "./influxdb_derive" }
